server:
  port: 8761
spring:
  application:
    name: eureka-ws
  boot:
    admin:
      client:
        url:
        - http://localhost:5000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true